 CC=g++
 CFLAGS=-c -Wall -Werror -std=c++11
 SOURCES=main.cpp
 OBJECTS=$(SOURCES:*.cpp=*.o)
 EXECUTABLE=calculator.exe

 all: $(SOURCES) $(EXECUTABLE)
	
 $(EXECUTABLE): $(OBJECTS) 
	    $(CC) $(LDFLAGS) $(OBJECTS) -o $@ -std=c++11

 build/%.o: src/%.cpp
	    $(CC) $(CFLAGS) $< -o $@

 .PHONY: clean
 clean:
        rm -rf *.o *.exe